# We define user www-data which on Nginx's processess runs
# Nginx adapts the numbers of workers to the number of available CPU
# Nginx works with a master and multiple workers, makes things faster because we split tasks
user www-data;
worker_processes  auto;

# We set the max number of simultaneous connections by worker (1024)
events {
    worker_connections 1024;
}

# http block: all of this block is a safety measure to avoid unwanted access
# mime.types: to associate extension of mime types (to tells browser what type is a file)
# if unknown extension, we send octet-stream (browser will suggest to download the file and not open it)
# allow to send directly static files (faster)
# 65s is the max delay to keep an open connection
# to activate gzip compression (reduce size of html, css, js files, therfore site is faster)
#   First server block: "catch-all":
#   - the server captures all https unexpected connections
#   - this include all servers which have not names
#   - therefore if someone unwanted tries to access our server, Nginx send a 444 code (no response) which cut directly the connection
#   Second server block: the true one (real site)
#   - server only available to fpaulas-.42.fr
#   - root of site (wp_data)
#   - default page (index.php)
#   - when a client ask for something, Nginx first try is an exact file ($uri), then a folder ($uri/) and finally redirects to index.php
#   - Special block for PHP files:
#       - sends PHP request to WP container on port 9000 (which used by PHP-FPM to listen)
#       - tells to PHP-FPM which file to execute
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    gzip on;

    server {
        listen 443 ssl default_server;
        server_name _;
        
        ssl_certificate		/etc/nginx/ssl/fpaulas-.crt;
        ssl_certificate_key	/etc/nginx/ssl/fpaulas-.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        
        return 444;
    }

    server {
        listen 443 ssl;
        server_name fpaulas-.42.fr;

        ssl_certificate		/etc/nginx/ssl/fpaulas-.crt;
        ssl_certificate_key	/etc/nginx/ssl/fpaulas-.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        }
    }
}